#!/usr/bin/env node
// Builds LEDGER-INDEX.md: one row per EVIDENCE_LEDGER.md record, so an agent
// can see the project's current standing without reading the whole ledger.
//
// The ledger stays the authority. This index is derived from it and says so.
// `--check` exits non-zero when the committed index no longer matches what the
// ledger would generate, so a stale index is caught instead of trusted.

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const LEDGER = path.join(ROOT, 'EVIDENCE_LEDGER.md');
const INDEX = path.join(ROOT, 'LEDGER-INDEX.md');

const CURRENT = ['accepted', 'narrowed', 'provisional', 'open', 'stale'];
const TYPE_ORDER = ['FACT', 'DECISION', 'RESULT', 'CORRECTION', 'HYPOTHESIS', 'QUESTION'];
const CLAIM_LIMIT = 220;

// Every `### TYPE-NNNN — title` section, with its `- **field:** value` bullets.
// A `##` or `###` heading that is not a record ends the current record.
function parseLedgerRecords(text) {
  const records = [];
  let current = null;
  text.replace(/\r\n/g, '\n').split('\n').forEach((line, i) => {
    // Any dash between ID and title: a record the parser skips is a record no gate sees.
    const heading = /^### ([A-Z]+)-(\d{4})\s*[—–-]\s*(.*)$/.exec(line);
    if (heading) {
      current = { id: `${heading[1]}-${heading[2]}`, prefix: heading[1], number: Number(heading[2]),
        title: heading[3].trim(), line: i + 1, fields: {} };
      records.push(current);
      return;
    }
    if (/^#{2,3} /.test(line)) { current = null; return; }
    if (!current) return;
    const field = /^- \*\*([a-z_]+):\*\*\s*(.*)$/.exec(line);
    if (field) current.fields[field[1]] = field[1] === 'status' ? field[2].replace(/`/g, '').trim().toLowerCase() : field[2].trim();
  });
  return records;
}

function firstSentence(text) {
  const plain = text.replace(/\*\*/g, '').replace(/\s+/g, ' ').trim();
  const m = /^(.+?[.?!])(\s|$)/.exec(plain);
  const s = m ? m[1] : plain;
  return s.length > CLAIM_LIMIT ? `${s.slice(0, CLAIM_LIMIT - 1).trimEnd()}…` : s;
}

// Only the leading class name(s); the qualifying prose stays in the ledger.
function proofClasses(value = '') {
  const names = [...value.matchAll(/`([A-Za-z_]+)`/g)].map((m) => m[1]);
  return names.length ? [...new Set(names)].join(', ') : value.split(/\s/)[0] || '—';
}

function cell(text) { return String(text).replace(/\|/g, '\\|'); }

function row(r) {
  const claim = firstSentence(r.fields.statement || r.fields.question || r.title);
  return `| ${r.id} | ${cell(r.title)} | ${r.fields.status || '—'} | ${cell(proofClasses(r.fields.proof_class))} | ${cell(claim)} | ${r.line} |`;
}

function byType(a, b) {
  return TYPE_ORDER.indexOf(a.prefix) - TYPE_ORDER.indexOf(b.prefix) || a.number - b.number;
}

function renderIndex(records) {
  const current = records.filter((r) => CURRENT.includes(r.fields.status)).sort(byType);
  const retired = records.filter((r) => !CURRENT.includes(r.fields.status)).sort(byType);
  const counts = {};
  for (const r of records) counts[r.fields.status] = (counts[r.fields.status] || 0) + 1;
  const header = '| Record | Title | Status | Proof class | Claim (first sentence) | Ledger line |\n| --- | --- | --- | --- | --- | --- |';
  return [
    '# Ledger index',
    '',
    '<!-- Generated by tools/ledger-index.js from EVIDENCE_LEDGER.md. Do not edit by hand. -->',
    '',
    'Read this before the full ledger. It lists every record\'s standing in one line.',
    'It is navigation only: before relying on a claim, open its record in',
    '[EVIDENCE_LEDGER.md](EVIDENCE_LEDGER.md) at the listed line and follow its evidence.',
    'A `narrowed` record must be read together with the correction that narrowed it.',
    '',
    `Records: ${records.length} (${Object.entries(counts).sort().map(([k, v]) => `${v} ${k}`).join(', ')}).`,
    '',
    '## Current records',
    '',
    header,
    ...current.map(row),
    '',
    '## Superseded or rejected records',
    '',
    'Kept for history. Their claims no longer hold as stated; see the listed replacement.',
    '',
    '| Record | Title | Status | Replaced by | Ledger line |\n| --- | --- | --- | --- | --- |',
    ...retired.map((r) => `| ${r.id} | ${cell(r.title)} | ${r.fields.status || '—'} | ${cell(r.fields.superseded_by || '—')} | ${r.line} |`),
    '',
  ].join('\n');
}

function main() {
  const records = parseLedgerRecords(fs.readFileSync(LEDGER, 'utf8'));
  const expected = renderIndex(records);
  if (process.argv.includes('--check')) {
    const actual = fs.existsSync(INDEX) ? fs.readFileSync(INDEX, 'utf8').replace(/\r\n/g, '\n') : '';
    if (actual !== expected) {
      console.error('LEDGER INDEX STALE: run `node tools/ledger-index.js` and commit LEDGER-INDEX.md');
      process.exitCode = 1;
      return;
    }
    console.log('LEDGER INDEX CURRENT');
    return;
  }
  fs.writeFileSync(INDEX, expected);
  console.log(`wrote LEDGER-INDEX.md (${records.length} records)`);
}

if (require.main === module) main();

module.exports = { parseLedgerRecords, renderIndex, firstSentence, proofClasses };
